### ISSUE TITLE
ss-server.exe怎么用interface参数?

### ISSUE THREAD

**Issue by zhengtong0898** [DDoSolitary/shadowsocks-libev-win#1]
我的笔记本电脑上有: 
        WLAN 连接的是手机分享出来的4G热点.
        以太网 连接的是网线.

通过下面命令预期是请求到这个端口的流量, 都走WLAN网卡, 但是实际上还是走以太网网卡.
ss-server.exe -s 192.168.43.243 -p 8388 -k xxxxxx -i WLAN

这种情况该如何解决呢?

**Comment by DDoSolitary** [comment]
用 -b 选项指定WLAN的本地IP，或者使用软件ForceBindIP
