### ISSUE TITLE
Connection Timeout even if it's still running

### ISSUE THREAD

**Issue by ryandotnet** [DDoSolitary/shadowsocks-libev-win#2]
Hello! I'm using your most recent build of x86_x64.

However I'm getting an issue of any connection getting closed after the set timeout period even if packets/data is still getting sent through. I send game data through Shadowsocks.

If I set ss-local timeout = 60s, I get disconnected from game after 60s.
If I set it to 600s, I get disconnected from game after 600s.

Is this a bug? If not, is there a way around this? Thank you!

EDIT: This doesn't happen with shadowsocks windows GUI client.

**Comment by DDoSolitary** [comment]
I'm afraid I can help because I'm not very familiar with shadowsocks' codebase. I think you can ask at https://github.com/shadowsocks/shadowsocks-libev/issues. Cygwin compilation is supported by shadowsocks' dev if I remember correctly.

**Comment by ryandotnet** [comment]
All good! Thank you for taking the time to reply ^^. 

If it's alright with you, I still have one more question ><. I was wondering what steps you took to compile it in Cygwin and how you got those cyg***.dll's? If not please feel free to close this issue!

Thanks again.

**Comment by DDoSolitary** [comment]
All the magic happens here https://github.com/DDoSolitary/shadowsocks-libev-win/blob/master/build.sh, and the DLLs are copied on line 56.

**Comment by ryandotnet** [comment]
Oh that's awesome! Thank you!

If I wanted to remove / not compile obfs I can just remove anything related to it from the build.sh right?

**Comment by DDoSolitary** [comment]
Ofc
