### ISSUE TITLE
ERROR: tcp fast open is not supported by this environment

### ISSUE THREAD

**Issue by Aniark** [DDoSolitary/shadowsocks-libev-win#3]
Win10 64位，使用ss-local.exe时，出现了`ERROR: tcp fast open is not supported by this environment`的报错

尝试过如下方案：
1、切换x86_64和x86版本，无效
2、将根目录下dll复制到system32及SysWOW64目录下，无效
3、使用管理员权限运行ss-local.exe，无效

但是使用我自己上个月编译的的ss-local.exe，则能够正常使用tcp fast open

**Comment by DDoSolitary** [comment]
我这里是用Cygwin编译的，但是目前Cygwin不支持TCP Fast Open，没有定义TCP_FASTOPEN常量，所以就会显示这个错误。你自己编译时可能是用MinGW编译的，MinGW直接调用的WinSock的API，而WinSock是支持Fast Open的
