### ISSUE TITLE
能否提供dll 版本

### ISSUE THREAD

**Issue by yunfengwangluo** [DDoSolitary/shadowsocks-libev-win#5]
我这里一直用 这里的 编译好的 ss-libev  感觉很不错  能否 制作 windows动态库dll 版本的 ss-libev  我这里 制作其它程序时 方便调用 感激不尽

**Comment by DDoSolitary** [comment]
已经加上了（这会儿正在编译，过几分钟应该就好了）
有两点提醒一下
- 我的脚本拿的是最新的commit而不是最新的稳定版本编译的（因为懒），如果用我这里编译出来的库要小心出现兼容性问题
- 我是用Cygwin编译的，所以你调用这个库的程序最好也是用Cygwin，如果是MSVC或者MinGW编译的程序来调用Cygwin的DLL的话很容易出问题。（我之前也尝试过编译MinGW版本，但是libcork好像不支持，就放弃了）

**Comment by yunfengwangluo** [comment]
感觉您对我这个了 需要的支持 刚刚下载了一些 里面的确有了 dll 和 dll.a&nbsp; 但是缺少一个 调用 dll接口的头文件 .h 或者 说明文档&nbsp;


我简单说一下 我这里的情况 正在做一款 游戏加速器 目前打算用ss 和ssr 作为主要连接 其中测试了很多个不同语言写的 ss 版本 都或多或少出现了一些问题&nbsp; 只有这个ss-libev 在windows 系统下 表现非常好 所以就计划 把这个作为我的主要程序&nbsp; 但由于我个人技术不行 无法看明白这个源码 基本来说 我c\c++ 还处于 只会写&nbsp; HW 的水平&nbsp; 但中间也了解了一些问题 例如 libev 库 不支持 windows 上面调用 所以就萌生了 做成动态库的想法
我这里的程序员 水平有限 只会 一点简单的c++技术 例如 折腾 软件ui 等&nbsp; 这个棘手的问题没想到 哥哥 这么快就可以搞定&nbsp; 所以想让哥哥 提供一些帮助我这里 可以出10000-20000 作为报酬


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"DDoSolitary"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月1日(星期五) 晚上11:35
收件人:&nbsp;"DDoSolitary/shadowsocks-libev-win"<shadowsocks-libev-win@noreply.github.com&gt;;
抄送:&nbsp;"you can"<2538868876@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DDoSolitary/shadowsocks-libev-win] 能否提供dll 版本 (#5)





 
已经加上了（这会儿正在编译，过几分钟应该就好了）
 有两点提醒一下
  
我的脚本拿的是最新的commit而不是最新的稳定版本编译的（因为懒），如果用我这里编译出来的库要小心出现兼容性问题
 
我是用Cygwin编译的，所以你调用这个库的程序最好也是用Cygwin，如果是MSVC或者MinGW编译的程序来调用Cygwin的DLL的话很容易出问题。（我之前也尝试过编译MinGW版本，但是libcork好像不支持，就放弃了）
